version: "3"
services:
  mongo:
    image: mongo:4.4.13
    environment:
      MONGO_INITDB_DATABASE: open5gs
    container_name: mongo
    volumes:
      - ./mongodb:/data/db
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "27017/udp"
      - "27017/tcp"
    command: mongod --bind_ip 0.0.0.0
    restart: on-failure
    networks:
      default:
        ipv4_address: 172.22.0.2
  webui:
    image: gradiant/open5gs-webui:2.4.11
    container_name: webui
    depends_on:
      - mongo
    environment:
      - DB_URI=mongodb://mongo/open5gs
      - NODE_ENV=dev
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "3000/tcp"
    ports:
      - "3000:3000/tcp"
    restart: on-failure
    networks:
      default:
        ipv4_address: 172.22.0.26
  hss:
    image: gradiant/open5gs:2.4.13
    entrypoint: /entrypoint_open5gs.sh
    container_name: hss
    command: open5gs-hssd
    volumes:
      - ./config/open5gs/entrypoint_open5gs.sh:/entrypoint_open5gs.sh
      - ./config/open5gs/hss.conf:/opt/open5gs/etc/freeDiameter/hss.conf
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - mongo
    environment:
      - DB_URI=mongodb://mongo/open5gs
    expose:
      - "3868/udp"
      - "3868/tcp"
      - "3868/sctp"
      - "5868/udp"
      - "5868/tcp"
      - "5868/sctp"
    restart: on-failure
    networks:
      default:
        ipv4_address: 172.22.0.3
  sgwc:
    image: gradiant/open5gs:2.4.13
    entrypoint: /entrypoint_open5gs.sh
    command: open5gs-sgwcd
    depends_on:
      - smf
      - upf
    container_name: sgwc
    volumes:
      - ./config/open5gs/entrypoint_open5gs.sh:/entrypoint_open5gs.sh
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "2123/udp"
      - "8805/udp"
    restart: on-failure
    networks:
      default:
        ipv4_address: 172.22.0.5
  sgwu:
    image: gradiant/open5gs:2.4.13
    entrypoint: /entrypoint_open5gs.sh
    command: open5gs-sgwud
    depends_on:
      - smf
      - upf
    container_name: sgwu
    volumes:
      - ./config/open5gs/entrypoint_open5gs.sh:/entrypoint_open5gs.sh
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "8805/udp"
      - "2152/udp"
    restart: on-failure
    networks:
      default:
        ipv4_address: 172.22.0.6
  smf:
    image: gradiant/open5gs:2.4.13
    entrypoint: /entrypoint_open5gs.sh
    command: open5gs-smfd
    container_name: smf
    volumes:
      - ./config/open5gs/entrypoint_open5gs.sh:/entrypoint_open5gs.sh
      - ./config/open5gs/smf.conf:/opt/open5gs/etc/freeDiameter/smf.conf
      - ./config/open5gs/smf.yaml:/opt/open5gs/smf.yaml
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "3868/udp"
      - "3868/tcp"
      - "3868/sctp"
      - "5868/udp"
      - "5868/tcp"
      - "5868/sctp"
      - "8805/udp"
      - "2123/udp"
      - "7777/tcp"
    restart: on-failure
    networks:
      default:
        ipv4_address: 172.22.0.7        
  upf:
    image: gradiant/open5gs:2.4.13
    entrypoint: /entrypoint_open5gs.sh
    command: open5gs-upfd
    depends_on:
      - smf
    container_name: upf
    volumes:
      - ./config/open5gs/entrypoint_open5gs.sh:/entrypoint_open5gs.sh
      - ./config/open5gs/upf.yaml:/opt/open5gs/etc/open5gs/upf.yaml
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "2152/udp"
      - "8805/udp"
    ports:
      - 2152:2152
    cap_add:
      - all
    privileged: true
    sysctls:
      - net.ipv4.ip_forward=1
    restart: on-failure
    networks:
      default:
        ipv4_address: 172.22.0.8
  mme:
    image: gradiant/open5gs:2.4.13
    entrypoint: /entrypoint_open5gs.sh
    command: open5gs-mmed
    depends_on:
      - hss
      - sgwc
      - sgwu
      - smf
      - upf
    container_name: mme
    volumes:
      - ./config/open5gs/entrypoint_open5gs.sh:/entrypoint_open5gs.sh
      - ./config/open5gs/mme.yaml:/opt/open5gs/etc/open5gs/mme.yaml
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "3868/udp"
      - "3868/tcp"
      - "3868/sctp"
      - "5868/udp"
      - "5868/tcp"
      - "5868/sctp"
      - "36412/sctp"
      - "2123/udp"
    ports:
      - 36412:36412
    restart: on-failure
    networks:
      default:
        ipv4_address: 172.22.0.9
  pcrf:
    image: gradiant/open5gs:2.4.13
    entrypoint: /entrypoint_open5gs.sh
    command: open5gs-pcrfd
    container_name: pcrf
    environment:
      - DB_URI=mongodb://mongo/open5gs
    depends_on:
      - mongo
    volumes:
      - ./config/open5gs/entrypoint_open5gs.sh:/entrypoint_open5gs.sh
      - ./config/open5gs/pcrf.conf:/opt/open5gs/etc/freeDiameter/pcrf.conf
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "3868/udp"
      - "3868/tcp"
      - "3868/sctp"
      - "5868/udp"
      - "5868/tcp"
      - "5868/sctp"
    restart: on-failure
    networks:
      default:
        ipv4_address: 172.22.0.4

networks:
  default:
    ipam:
      config:
        - subnet: 172.22.0.0/24
