version: "3"
services:
  mongo:
    image: bitnami/mongodb:4.4.1-debian-10-r39
    container_name: mongo
    environment:
      MONGO_INITDB_DATABASE: open5gs
    volumes:
      - ./mongodb:/data/db
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "27017/udp"
      - "27017/tcp"
    command: mongod --bind_ip 0.0.0.0
    restart: on-failure
    networks:
      default:
        ipv4_address: 172.22.0.2

  webui:
    image: docker.io/gradiant/open5gs-webui:2.7.0
    container_name: webui
    depends_on:
      - mongo
    environment:
      - DB_URI=mongodb://mongo/open5gs
      - NODE_ENV=dev
    expose:
      - "9999/tcp"
    ports:
      - "3000:9999"
    restart: on-failure
    networks:
      default:
        ipv4_address: 172.22.0.3

  nrf:
    image: docker.io/gradiant/open5gs:2.7.0
    entrypoint: /entrypoint_open5gs.sh
    command: open5gs-nrfd
    container_name: nrf
    volumes:
      - ./config/open5gs/entrypoint_open5gs.sh:/entrypoint_open5gs.sh
      #- ./config/open5gs/nrf.yaml:/opt/open5gs/etc/open5gs/nrf.yaml
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      default:
        ipv4_address: 172.22.0.4

  amf:
    image: docker.io/gradiant/open5gs:2.7.0
    entrypoint: /entrypoint_open5gs.sh
    command: open5gs-amfd
    container_name: amf
    volumes:
      - ./config/open5gs/entrypoint_open5gs.sh:/entrypoint_open5gs.sh
      #- ./config/open5gs/amf.yaml:/opt/open5gs/etc/open5gs/amf.yaml
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "38412:38412/tcp"
      - "38412:38412/udp"
    networks:
      default:
        ipv4_address: 172.22.0.5

  ausf:
    image: docker.io/gradiant/open5gs:2.7.0
    entrypoint: /entrypoint_open5gs.sh
    command: open5gs-ausfd
    container_name: ausf
    volumes:
      - ./config/open5gs/entrypoint_open5gs.sh:/entrypoint_open5gs.sh
      #- ./config/open5gs/ausf.yaml:/opt/open5gs/etc/open5gs/ausf.yaml
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      default:
        ipv4_address: 172.22.0.6

  udm:
    image: docker.io/gradiant/open5gs:2.7.0
    entrypoint: /entrypoint_open5gs.sh
    command: open5gs-udmd
    container_name: udm
    volumes:
      - ./config/open5gs/entrypoint_open5gs.sh:/entrypoint_open5gs.sh
      #- ./config/open5gs/udm.yaml:/opt/open5gs/etc/open5gs/udm.yaml
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      default:
        ipv4_address: 172.22.0.7

  pcf:
    image: docker.io/gradiant/open5gs:2.7.0
    entrypoint: /entrypoint_open5gs.sh
    command: open5gs-pcfd
    container_name: pcf
    volumes:
      - ./config/open5gs/entrypoint_open5gs.sh:/entrypoint_open5gs.sh
      #- ./config/open5gs/pcf.yaml:/opt/open5gs/etc/open5gs/pcf.yaml
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      default:
        ipv4_address: 172.22.0.8

  smf:
    image: docker.io/gradiant/open5gs:2.7.0
    entrypoint: /entrypoint_open5gs.sh
    command: open5gs-smfd
    container_name: smf
    volumes:
      - ./config/open5gs/entrypoint_open5gs.sh:/entrypoint_open5gs.sh
      #- ./config/open5gs/smf.yaml:/opt/open5gs/etc/open5gs/smf.yaml
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "7777:7777"
    networks:
      default:
        ipv4_address: 172.22.0.9

  upf:
    image: docker.io/gradiant/open5gs:2.7.0
    entrypoint: /entrypoint_open5gs.sh
    command: open5gs-upfd
    container_name: upf
    volumes:
      - ./config/open5gs/entrypoint_open5gs.sh:/entrypoint_open5gs.sh
      #- ./config/open5gs/upf.yaml:/opt/open5gs/etc/open5gs/upf.yaml
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    cap_add:
      - all
    privileged: true
    sysctls:
      - net.ipv4.ip_forward=1
    ports:
      - "2152:2152/udp"
    networks:
      default:
        ipv4_address: 172.22.0.10

#  gnb:
#    image: gradiant/srsran-5g:24_10_1
#    container_name: gnb
#    networks:
#      default:
#        ipv4_address: 172.22.0.20
#    command: >
#      gnb
#      --rf.device=zmq
#      --zmq.bind_addr=ipc:///tmp/gnb
#      --log.all_level=debug
#    volumes:
#      - /tmp:/tmp
#    depends_on:
#      - amf

#  ue:
#    image: gradiant/srsran-5g:24_10_1
#    container_name: ue
#    networks:
#      default:
#        ipv4_address: 172.22.0.21
#    command: >
#      ue
#      --rf.device=zmq
#      --zmq.connect_addr=ipc:///tmp/gnb
#      --usim.imsi=001010000000001
#      --usim.k=465B5CE8B199B49FAA5F0A2EE238A6BC
#      --usim.opc=E8ED289DEBA952E4283B54E88E6183CA
#      --log.all_level=info
#    volumes:
#      - /tmp:/tmp
#    depends_on:
#      - gnb

networks:
  default:
    ipam:
      config:
        - subnet: 172.22.0.0/24
